---
title: "Basketball Salary"
author: "Ben Stano, ADD NAMES"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Baseketballs Brooooo

```{r, message=FALSE}
library(tidyverse)
```

## Importing Data

```{r}
# players <- read_csv("../data/players.csv")
# stats.36 <- read_csv("../data/PlayerStatisticsPer36Min.csv")
# stats.100 <- read_csv("../data/PlayerStatisticsPer100Poss.csv")
# stats.g <- read_csv("../data/PlayerStatisticsPerGame.csv")
# # salary <- read_csv("../data/salaries_1985to2018.csv")
# salary2 <- read_csv("../data/nba-salaries.csv")
```

## Cleaning and Merging Data

```{r}
# stats.g <- stats.g %>%
#   mutate(name = str_replace(Player, "\\*", ""))
# stats.g <- stats.g %>%
#   mutate(key = str_c(name, as.character(year), sep = ""))
# salary2 <- salary2 %>%
#   mutate(key = str_c(name, as.character(season), sep = ""))
```

### Joining the Datasets

```{r}
# final.data <- players %>%
#   inner_join(salary2, by = "name") %>%
#   inner_join(stats.g, by = "key") %>%
#   select(-key) %>%
#   filter(year >= 2017)
# 
# write_csv(final.data, "../data/final_data.csv")

bdata.raw <- read_csv("../data/final_data.csv")
```

### Cleaning the Data

```{r}
bdata.raw <- read_csv("../data/final_data.csv")
# displaying null values in each column
bdata.raw %>%
  map_dbl(~sum(is.na(.))) %>%
  unname() ->
na.dbl

na.cols <- data.frame("variable" = colnames(bdata.raw),
                      "null.count" = na.dbl)

na.cols %>%
  filter(null.count > 0)

# parsing numbers from difficult columns
bdata.raw$career_FG3_P <- parse_number(as.character(bdata.raw$`career_FG3%`))
bdata.raw$career_FG_P <- parse_number(as.character(bdata.raw$`career_FG%`))
bdata.raw$career_FT_P <- parse_number(as.character(bdata.raw$`career_FT%`))
# cleaning height
heights <- str_split(bdata.raw$height, "\\-")
heights.df <- t(data.frame(heights))
heights.int <- as.integer(heights.df[,1]) * 12 + as.integer(heights.df[,2])
bdata.raw$height <- heights.int

bdata.raw %>%
  mutate(draft_pick = parse_number(draft_pick),
         draft_round = parse_number(draft_round),
         shoots_right = ifelse(str_detect(shoots, "Right"),1,0),
         weight = parse_number(weight),
         Pos = as.factor(Pos)) %>%
  rename(career_eFG_P = `career_eFG%`,
         FG_P = `FG%`,
         THREEP_P = `3P%`,
         TWOP_P = `2P%`,
         eFG_P = `eFG%`,
         FT_P = `FT%`) %>%
  select(-birthDate, -birthPlace, -college, -draft_team, -highSchool, -name.x,
         -position.x, -position.y, -team, -Player, -name.y, -season, -Tm,
         -`career_FG3%`, -`career_FG%`, -`career_FT%`, -shoots) %>%
  na.omit() ->
bdata.clean

bdata.clean %>%
  select(-`_id`) ->
bdata.model
```

```{r}
levels(bdata.model$Pos)
```

## Variables Names

 - **salary**: player salary 

## Dimensionality Reduction

```{r}
ols.init <- glm(salary ~ ., data = bdata.model)

summary(ols.init)

plot(ols.init, which = 1)

plot(ols.init, which = 2)
```

```{r, message=FALSE}
library(klaR)
library(car)

cond.index(ols.init, bdata.model)

vif(ols.init)
```

## Transforming the Respsonse Variable

```{r}
bdata.model %>%
  mutate(log_salary = log(salary)) -> 
bdata.log

bdata.log$salary <- NULL
```

```{r}
ols.log <- glm(log_salary ~ ., data = bdata.log)

summary(ols.log)

plot(ols.log, which = c(1, 2))

cond.index(ols.log, bdata.log)

vif(ols.log)
```
## Pieceise Model

```{r}
fit.piecewise = lm(log_salary ~ . + I((year-2013) * (year>2013)), data = bdata.log)

summary(fit.piecewise)

plot(fit.piecewise, which = c(1, 2))
```


### Ridge/LASSO

### Feature Engineering

## Modeling

Possible Models:

OLS Regression

WLS Regression

GLM Regression

Regression Trees

Splines


